Added a Search Input - Using the Event Binding ( ) to send the data typed in the search input from the Template to the Component
OBS: The other two types of Binding:
 - [ ] = Property binding, from Component to Template
 - {{ }} = Two way data binding, from Component to Template, and vice versa
 - ( ) = Event binding, from Template to Component

 Using the $any() to solve the error below:
  - error TS2339: Property 'value' does not exist on type 'EventTarget'.

Original expression:
 - (keyup)="filter = $event.target.value"

 Solved expression:
 - (keyup)="filter = $any($event.target).value"